// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema, HttpSearchParamsSerialized } from "zimic/http";

export type JikanSchema = HttpSchema<{
  "/anime/:id/full": {
    GET: JikanOperations["getAnimeFullById"];
  };
  "/anime/:id": {
    GET: JikanOperations["getAnimeById"];
  };
  "/anime/:id/characters": {
    GET: JikanOperations["getAnimeCharacters"];
  };
  "/anime/:id/staff": {
    GET: JikanOperations["getAnimeStaff"];
  };
  "/anime/:id/episodes": {
    GET: JikanOperations["getAnimeEpisodes"];
  };
  "/anime/:id/episodes/:episode": {
    GET: JikanOperations["getAnimeEpisodeById"];
  };
  "/anime/:id/news": {
    GET: JikanOperations["getAnimeNews"];
  };
  "/anime/:id/forum": {
    GET: JikanOperations["getAnimeForum"];
  };
  "/anime/:id/videos": {
    GET: JikanOperations["getAnimeVideos"];
  };
  "/anime/:id/videos/episodes": {
    GET: JikanOperations["getAnimeVideosEpisodes"];
  };
  "/anime/:id/pictures": {
    GET: JikanOperations["getAnimePictures"];
  };
  "/anime/:id/statistics": {
    GET: JikanOperations["getAnimeStatistics"];
  };
  "/anime/:id/moreinfo": {
    GET: JikanOperations["getAnimeMoreInfo"];
  };
  "/anime/:id/recommendations": {
    GET: JikanOperations["getAnimeRecommendations"];
  };
  "/anime/:id/userupdates": {
    GET: JikanOperations["getAnimeUserUpdates"];
  };
  "/anime/:id/reviews": {
    GET: JikanOperations["getAnimeReviews"];
  };
  "/anime/:id/relations": {
    GET: JikanOperations["getAnimeRelations"];
  };
  "/anime/:id/themes": {
    GET: JikanOperations["getAnimeThemes"];
  };
  "/anime/:id/external": {
    GET: JikanOperations["getAnimeExternal"];
  };
  "/anime/:id/streaming": {
    GET: JikanOperations["getAnimeStreaming"];
  };
  "/characters/:id/full": {
    GET: JikanOperations["getCharacterFullById"];
  };
  "/characters/:id": {
    GET: JikanOperations["getCharacterById"];
  };
  "/characters/:id/anime": {
    GET: JikanOperations["getCharacterAnime"];
  };
  "/characters/:id/manga": {
    GET: JikanOperations["getCharacterManga"];
  };
  "/characters/:id/voices": {
    GET: JikanOperations["getCharacterVoiceActors"];
  };
  "/characters/:id/pictures": {
    GET: JikanOperations["getCharacterPictures"];
  };
  "/clubs/:id": {
    GET: JikanOperations["getClubsById"];
  };
  "/clubs/:id/members": {
    GET: JikanOperations["getClubMembers"];
  };
  "/clubs/:id/staff": {
    GET: JikanOperations["getClubStaff"];
  };
  "/clubs/:id/relations": {
    GET: JikanOperations["getClubRelations"];
  };
  "/genres/anime": {
    GET: JikanOperations["getAnimeGenres"];
  };
  "/genres/manga": {
    GET: JikanOperations["getMangaGenres"];
  };
  "/magazines": {
    GET: JikanOperations["getMagazines"];
  };
  "/manga/:id/full": {
    GET: JikanOperations["getMangaFullById"];
  };
  "/manga/:id": {
    GET: JikanOperations["getMangaById"];
  };
  "/manga/:id/characters": {
    GET: JikanOperations["getMangaCharacters"];
  };
  "/manga/:id/news": {
    GET: JikanOperations["getMangaNews"];
  };
  "/manga/:id/forum": {
    GET: JikanOperations["getMangaTopics"];
  };
  "/manga/:id/pictures": {
    GET: JikanOperations["getMangaPictures"];
  };
  "/manga/:id/statistics": {
    GET: JikanOperations["getMangaStatistics"];
  };
  "/manga/:id/moreinfo": {
    GET: JikanOperations["getMangaMoreInfo"];
  };
  "/manga/:id/recommendations": {
    GET: JikanOperations["getMangaRecommendations"];
  };
  "/manga/:id/userupdates": {
    GET: JikanOperations["getMangaUserUpdates"];
  };
  "/manga/:id/reviews": {
    GET: JikanOperations["getMangaReviews"];
  };
  "/manga/:id/relations": {
    GET: JikanOperations["getMangaRelations"];
  };
  "/manga/:id/external": {
    GET: JikanOperations["getMangaExternal"];
  };
  "/people/:id/full": {
    GET: JikanOperations["getPersonFullById"];
  };
  "/people/:id": {
    GET: JikanOperations["getPersonById"];
  };
  "/people/:id/anime": {
    GET: JikanOperations["getPersonAnime"];
  };
  "/people/:id/voices": {
    GET: JikanOperations["getPersonVoices"];
  };
  "/people/:id/manga": {
    GET: JikanOperations["getPersonManga"];
  };
  "/people/:id/pictures": {
    GET: JikanOperations["getPersonPictures"];
  };
  "/producers/:id": {
    GET: JikanOperations["getProducerById"];
  };
  "/producers/:id/full": {
    GET: JikanOperations["getProducerFullById"];
  };
  "/producers/:id/external": {
    GET: JikanOperations["getProducerExternal"];
  };
  "/random/anime": {
    GET: JikanOperations["getRandomAnime"];
  };
  "/random/manga": {
    GET: JikanOperations["getRandomManga"];
  };
  "/random/characters": {
    GET: JikanOperations["getRandomCharacters"];
  };
  "/random/people": {
    GET: JikanOperations["getRandomPeople"];
  };
  "/random/users": {
    GET: JikanOperations["getRandomUsers"];
  };
  "/recommendations/anime": {
    GET: JikanOperations["getRecentAnimeRecommendations"];
  };
  "/recommendations/manga": {
    GET: JikanOperations["getRecentMangaRecommendations"];
  };
  "/reviews/anime": {
    GET: JikanOperations["getRecentAnimeReviews"];
  };
  "/reviews/manga": {
    GET: JikanOperations["getRecentMangaReviews"];
  };
  "/schedules": {
    GET: JikanOperations["getSchedules"];
  };
  "/anime": {
    GET: JikanOperations["getAnimeSearch"];
  };
  "/manga": {
    GET: JikanOperations["getMangaSearch"];
  };
  "/people": {
    GET: JikanOperations["getPeopleSearch"];
  };
  "/characters": {
    GET: JikanOperations["getCharactersSearch"];
  };
  "/users": {
    GET: JikanOperations["getUsersSearch"];
  };
  "/users/userbyid/:id": {
    GET: JikanOperations["getUserById"];
  };
  "/clubs": {
    GET: JikanOperations["getClubsSearch"];
  };
  "/producers": {
    GET: JikanOperations["getProducers"];
  };
  "/seasons/now": {
    GET: JikanOperations["getSeasonNow"];
  };
  "/seasons/:year/:season": {
    GET: JikanOperations["getSeason"];
  };
  "/seasons": {
    GET: JikanOperations["getSeasonsList"];
  };
  "/seasons/upcoming": {
    GET: JikanOperations["getSeasonUpcoming"];
  };
  "/top/anime": {
    GET: JikanOperations["getTopAnime"];
  };
  "/top/manga": {
    GET: JikanOperations["getTopManga"];
  };
  "/top/people": {
    GET: JikanOperations["getTopPeople"];
  };
  "/top/characters": {
    GET: JikanOperations["getTopCharacters"];
  };
  "/top/reviews": {
    GET: JikanOperations["getTopReviews"];
  };
  "/users/:username/full": {
    GET: JikanOperations["getUserFullProfile"];
  };
  "/users/:username": {
    GET: JikanOperations["getUserProfile"];
  };
  "/users/:username/statistics": {
    GET: JikanOperations["getUserStatistics"];
  };
  "/users/:username/favorites": {
    GET: JikanOperations["getUserFavorites"];
  };
  "/users/:username/userupdates": {
    GET: JikanOperations["getUserUpdates"];
  };
  "/users/:username/about": {
    GET: JikanOperations["getUserAbout"];
  };
  "/users/:username/history": {
    GET: JikanOperations["getUserHistory"];
  };
  "/users/:username/friends": {
    GET: JikanOperations["getUserFriends"];
  };
  "/users/:username/animelist": {
    GET: JikanOperations["getUserAnimelist"];
  };
  "/users/:username/mangalist": {
    GET: JikanOperations["getUserMangaList"];
  };
  "/users/:username/reviews": {
    GET: JikanOperations["getUserReviews"];
  };
  "/users/:username/recommendations": {
    GET: JikanOperations["getUserRecommendations"];
  };
  "/users/:username/clubs": {
    GET: JikanOperations["getUserClubs"];
  };
  "/users/:username/external": {
    GET: JikanOperations["getUserExternal"];
  };
  "/watch/episodes": {
    GET: JikanOperations["getWatchRecentEpisodes"];
  };
  "/watch/episodes/popular": {
    GET: JikanOperations["getWatchPopularEpisodes"];
  };
  "/watch/promos": {
    GET: JikanOperations["getWatchRecentPromos"];
  };
  "/watch/promos/popular": {
    GET: JikanOperations["getWatchPopularPromos"];
  };
}>;

export interface JikanComponents {
  schemas: {
    user_anime_list_status_filter: "all" | "watching" | "completed" | "onhold" | "dropped" | "plantowatch";
    anime_search_query_orderby: "mal_id" | "title" | "start_date" | "end_date" | "episodes" | "score" | "scored_by" | "rank" | "popularity" | "members" | "favorites";
    anime_search_query_rating: "g" | "pg" | "pg13" | "r17" | "r" | "rx";
    anime_search_query_status: "airing" | "complete" | "upcoming";
    anime_search_query_type: "tv" | "movie" | "ova" | "special" | "ona" | "music" | "cm" | "pv" | "tv_special";
    characters_search_query_orderby: "mal_id" | "name" | "favorites";
    club_search_query_category: "anime" | "manga" | "actors_and_artists" | "characters" | "cities_and_neighborhoods" | "companies" | "conventions" | "games" | "japan" | "music" | "other" | "schools";
    club_search_query_orderby: "mal_id" | "name" | "members_count" | "created";
    club_search_query_type: "public" | "private" | "secret";
    users_search_query_gender: "any" | "male" | "female" | "nonbinary";
    genre_query_filter: "genres" | "explicit_genres" | "themes" | "demographics";
    magazines_query_orderby: "mal_id" | "name" | "count";
    user_manga_list_status_filter: "all" | "reading" | "completed" | "onhold" | "dropped" | "plantoread";
    manga_search_query_orderby: "mal_id" | "title" | "start_date" | "end_date" | "chapters" | "volumes" | "score" | "scored_by" | "rank" | "popularity" | "members" | "favorites";
    manga_search_query_status: "publishing" | "complete" | "hiatus" | "discontinued" | "upcoming";
    manga_search_query_type: "manga" | "novel" | "lightnovel" | "oneshot" | "doujin" | "manhwa" | "manhua";
    people_search_query_orderby: "mal_id" | "name" | "birthday" | "favorites";
    producers_query_orderby: "mal_id" | "count" | "favorites" | "established";
    search_query_sort: "desc" | "asc";
    top_anime_filter: "airing" | "upcoming" | "bypopularity" | "favorite";
    top_manga_filter: "publishing" | "upcoming" | "bypopularity" | "favorite";
    top_reviews_type_enum: "anime" | "manga";
    anime_episodes: {
      data?: {
        mal_id?: number;
        url?: string | null;
        title?: string;
        title_japanese?: string | null;
        title_romanji?: string | null;
        duration?: number | null;
        aired?: string | null;
        filler?: boolean;
        recap?: boolean;
        forum_url?: string | null;
      }[];
    } & JikanComponents["schemas"]["pagination"];
    anime_news: JikanComponents["schemas"]["pagination"] & JikanComponents["schemas"]["news"];
    anime_videos_episodes: {
      data?: {
        mal_id?: number;
        title?: string;
        episode?: string;
        url?: string;
        images?: JikanComponents["schemas"]["common_images"];
      }[];
    } & JikanComponents["schemas"]["pagination"];
    character_pictures: {
      data?: {
        image_url?: string | null;
        large_image_url?: string | null;
      }[];
    };
    club_member: {
      data?: {
        username?: string;
        url?: string;
        images?: JikanComponents["schemas"]["user_images"];
      }[];
    };
    manga_news: JikanComponents["schemas"]["pagination"] & JikanComponents["schemas"]["news"];
    manga_pictures: {
      data?: JikanComponents["schemas"]["manga_images"][];
    };
    person_pictures: {
      data?: JikanComponents["schemas"]["people_images"][];
    };
    schedules: {
      data?: JikanComponents["schemas"]["anime"][];
    } & JikanComponents["schemas"]["pagination_plus"];
    users_search: {
      data?: {
        url?: string;
        username?: string;
        images?: JikanComponents["schemas"]["user_images"];
        last_online?: string;
      }[];
    } & JikanComponents["schemas"]["pagination"];
    seasons: {
      data?: {
        year?: number;
        seasons?: string[];
      }[];
    };
    user_friends: {
      data?: ({
        user?: JikanComponents["schemas"]["user_meta"];
      } & {
        last_online?: string;
        friends_since?: string;
      })[];
    } & JikanComponents["schemas"]["pagination"];
    user_clubs: {
      data?: {
        mal_id?: number;
        name?: string;
        url?: string;
      }[];
    } & JikanComponents["schemas"]["pagination"];
    watch_episodes: {
      data?: {
        entry?: JikanComponents["schemas"]["anime_meta"];
        episodes?: {
          mal_id?: string;
          url?: string;
          title?: string;
          premium?: boolean;
        }[];
        region_locked?: boolean;
      }[];
    } & JikanComponents["schemas"]["pagination"];
    watch_promos: JikanComponents["schemas"]["pagination"] & ({
      title?: string;
    } & {
      data?: {
        entry?: JikanComponents["schemas"]["anime_meta"];
        trailer?: JikanComponents["schemas"]["trailer"][];
      }[];
    });
    anime_characters: {
      data?: {
        character?: {
          mal_id?: number;
          url?: string;
          images?: JikanComponents["schemas"]["character_images"];
          name?: string;
        };
        role?: string;
        voice_actors?: {
          person?: {
            mal_id?: number;
            url?: string;
            images?: JikanComponents["schemas"]["people_images"];
            name?: string;
          };
          language?: string;
        }[];
      }[];
    };
    anime_search: {
      data?: JikanComponents["schemas"]["anime"][];
    } & JikanComponents["schemas"]["pagination_plus"];
    anime_episode: {
      mal_id?: number;
      url?: string;
      title?: string;
      title_japanese?: string | null;
      title_romanji?: string | null;
      duration?: number | null;
      aired?: string | null;
      filler?: boolean;
      recap?: boolean;
      synopsis?: string | null;
    };
    anime_full: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["anime_images"];
      trailer?: JikanComponents["schemas"]["trailer_base"];
      approved?: boolean;
      titles?: JikanComponents["schemas"]["title"][];
      title?: string;
      title_english?: string | null;
      title_japanese?: string | null;
      title_synonyms?: string[];
      type?: "TV" | "OVA" | "Movie" | "Special" | "ONA" | "Music" | null;
      source?: string | null;
      episodes?: number | null;
      status?: "Finished Airing" | "Currently Airing" | "Not yet aired" | null;
      airing?: boolean;
      aired?: JikanComponents["schemas"]["daterange"];
      duration?: string | null;
      rating?: "G - All Ages" | "PG - Children" | "PG-13 - Teens 13 or older" | "R - 17+ (violence & profanity)" | "R+ - Mild Nudity" | "Rx - Hentai" | null;
      score?: number | null;
      scored_by?: number | null;
      rank?: number | null;
      popularity?: number | null;
      members?: number | null;
      favorites?: number | null;
      synopsis?: string | null;
      background?: string | null;
      season?: "summer" | "winter" | "spring" | "fall" | null;
      year?: number | null;
      broadcast?: JikanComponents["schemas"]["broadcast"];
      producers?: JikanComponents["schemas"]["mal_url"][];
      licensors?: JikanComponents["schemas"]["mal_url"][];
      studios?: JikanComponents["schemas"]["mal_url"][];
      genres?: JikanComponents["schemas"]["mal_url"][];
      explicit_genres?: JikanComponents["schemas"]["mal_url"][];
      themes?: JikanComponents["schemas"]["mal_url"][];
      demographics?: JikanComponents["schemas"]["mal_url"][];
      relations?: {
        relation?: string;
        entry?: JikanComponents["schemas"]["mal_url"][];
      }[];
      theme?: {
        openings?: string[];
        endings?: string[];
      };
      external?: {
        name?: string;
        url?: string;
      }[];
      streaming?: {
        name?: string;
        url?: string;
      }[];
    };
    anime: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["anime_images"];
      trailer?: JikanComponents["schemas"]["trailer_base"];
      approved?: boolean;
      titles?: JikanComponents["schemas"]["title"][];
      title?: string;
      title_english?: string | null;
      title_japanese?: string | null;
      title_synonyms?: string[];
      type?: "TV" | "OVA" | "Movie" | "Special" | "ONA" | "Music" | null;
      source?: string | null;
      episodes?: number | null;
      status?: "Finished Airing" | "Currently Airing" | "Not yet aired" | null;
      airing?: boolean;
      aired?: JikanComponents["schemas"]["daterange"];
      duration?: string | null;
      rating?: "G - All Ages" | "PG - Children" | "PG-13 - Teens 13 or older" | "R - 17+ (violence & profanity)" | "R+ - Mild Nudity" | "Rx - Hentai" | null;
      score?: number | null;
      scored_by?: number | null;
      rank?: number | null;
      popularity?: number | null;
      members?: number | null;
      favorites?: number | null;
      synopsis?: string | null;
      background?: string | null;
      season?: "summer" | "winter" | "spring" | "fall" | null;
      year?: number | null;
      broadcast?: JikanComponents["schemas"]["broadcast"];
      producers?: JikanComponents["schemas"]["mal_url"][];
      licensors?: JikanComponents["schemas"]["mal_url"][];
      studios?: JikanComponents["schemas"]["mal_url"][];
      genres?: JikanComponents["schemas"]["mal_url"][];
      explicit_genres?: JikanComponents["schemas"]["mal_url"][];
      themes?: JikanComponents["schemas"]["mal_url"][];
      demographics?: JikanComponents["schemas"]["mal_url"][];
    };
    anime_staff: {
      data?: {
        person?: {
          mal_id?: number;
          url?: string;
          images?: JikanComponents["schemas"]["people_images"];
          name?: string;
        };
        positions?: string[];
      }[];
    };
    anime_statistics: {
      data?: {
        watching?: number;
        completed?: number;
        on_hold?: number;
        dropped?: number;
        plan_to_watch?: number;
        total?: number;
        scores?: {
          score?: number;
          votes?: number;
          percentage?: number;
        }[];
      };
    };
    anime_themes: {
      data?: {
        openings?: string[];
        endings?: string[];
      };
    };
    anime_videos: {
      data?: {
        promo?: {
          title?: string;
          trailer?: JikanComponents["schemas"]["trailer"];
        }[];
        episodes?: {
          mal_id?: number;
          url?: string;
          title?: string;
          episode?: string;
          images?: JikanComponents["schemas"]["common_images"];
        }[];
        music_videos?: {
          title?: string;
          video?: JikanComponents["schemas"]["trailer"];
          meta?: {
            title?: string | null;
            author?: string | null;
          };
        }[];
      };
    };
    character_anime: {
      data?: {
        role?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
      }[];
    };
    characters_search: {
      data?: JikanComponents["schemas"]["character"][];
    } & JikanComponents["schemas"]["pagination_plus"];
    character_full: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["character_images"];
      name?: string;
      name_kanji?: string | null;
      nicknames?: string[];
      favorites?: number;
      about?: string | null;
      anime?: {
        role?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
      }[];
      manga?: {
        role?: string;
        manga?: JikanComponents["schemas"]["manga_meta"];
      }[];
      voices?: {
        language?: string;
        person?: JikanComponents["schemas"]["person_meta"];
      }[];
    };
    character_manga: {
      data?: {
        role?: string;
        manga?: JikanComponents["schemas"]["manga_meta"];
      }[];
    };
    character: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["character_images"];
      name?: string;
      name_kanji?: string | null;
      nicknames?: string[];
      favorites?: number;
      about?: string | null;
    };
    character_voice_actors: {
      data?: {
        language?: string;
        person?: JikanComponents["schemas"]["person_meta"];
      }[];
    };
    clubs_search: {
      data?: JikanComponents["schemas"]["club"][];
    } & JikanComponents["schemas"]["pagination"];
    club_relations: {
      data?: {
        anime?: JikanComponents["schemas"]["mal_url"][];
        manga?: JikanComponents["schemas"]["mal_url"][];
        characters?: JikanComponents["schemas"]["mal_url"][];
      };
    };
    club: {
      mal_id?: number;
      name?: string;
      url?: string;
      images?: JikanComponents["schemas"]["common_images"];
      members?: number;
      category?: "actors & artists" | "anime" | "characters" | "cities & neighborhoods" | "companies" | "conventions" | "games" | "japan" | "manga" | "music" | "others" | "schools";
      created?: string;
      access?: "public" | "private" | "secret";
    };
    club_staff: {
      data?: {
        url?: string;
        username?: string;
      }[];
    };
    trailer: JikanComponents["schemas"]["trailer_base"] & JikanComponents["schemas"]["trailer_images"];
    trailer_base: {
      youtube_id?: string | null;
      url?: string | null;
      embed_url?: string | null;
    };
    trailer_images: {
      images?: {
        image_url?: string | null;
        small_image_url?: string | null;
        medium_image_url?: string | null;
        large_image_url?: string | null;
        maximum_image_url?: string | null;
      };
    };
    daterange: {
      from?: string | null;
      to?: string | null;
      prop?: {
        from?: {
          day?: number | null;
          month?: number | null;
          year?: number | null;
        };
        to?: {
          day?: number | null;
          month?: number | null;
          year?: number | null;
        };
        string?: string | null;
      };
    };
    broadcast: {
      day?: string | null;
      time?: string | null;
      timezone?: string | null;
      string?: string | null;
    };
    mal_url: {
      mal_id?: number;
      type?: string;
      name?: string;
      url?: string;
    };
    mal_url_2: {
      mal_id?: number;
      type?: string;
      title?: string;
      url?: string;
    };
    relation: {
      relation?: string;
      entry?: JikanComponents["schemas"]["mal_url"][];
    };
    pagination: {
      pagination?: {
        last_visible_page?: number;
        has_next_page?: boolean;
      };
    };
    pagination_plus: {
      pagination?: {
        last_visible_page?: number;
        has_next_page?: boolean;
        items?: {
          count?: number;
          total?: number;
          per_page?: number;
        };
      };
    };
    user_meta: {
      username?: string;
      url?: string;
      images?: JikanComponents["schemas"]["user_images"];
    };
    user_by_id: {
      url?: string;
      username?: string;
    };
    user_images: {
      jpg?: {
        image_url?: string | null;
      };
      webp?: {
        image_url?: string | null;
      };
    };
    anime_meta: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["anime_images"];
      title?: string;
    };
    manga_meta: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["manga_images"];
      title?: string;
    };
    character_meta: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["character_images"];
      name?: string;
    };
    person_meta: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["people_images"];
      name?: string;
    };
    anime_images: {
      jpg?: {
        image_url?: string | null;
        small_image_url?: string | null;
        large_image_url?: string | null;
      };
      webp?: {
        image_url?: string | null;
        small_image_url?: string | null;
        large_image_url?: string | null;
      };
    };
    manga_images: {
      jpg?: {
        image_url?: string | null;
        small_image_url?: string | null;
        large_image_url?: string | null;
      };
      webp?: {
        image_url?: string | null;
        small_image_url?: string | null;
        large_image_url?: string | null;
      };
    };
    character_images: {
      jpg?: {
        image_url?: string | null;
        small_image_url?: string | null;
      };
      webp?: {
        image_url?: string | null;
        small_image_url?: string | null;
      };
    };
    people_images: {
      jpg?: {
        image_url?: string | null;
      };
    };
    common_images: {
      jpg?: {
        image_url?: string | null;
      };
    };
    title: {
      type?: string;
      title?: string;
    };
    external_links: {
      data?: {
        name?: string;
        url?: string;
      }[];
    };
    forum: {
      data?: {
        mal_id?: number;
        url?: string;
        title?: string;
        date?: string;
        author_username?: string;
        author_url?: string;
        comments?: number;
        last_comment?: {
          url?: string;
          author_username?: string;
          author_url?: string;
          date?: string | null;
        };
      }[];
    };
    genres: {
      data?: JikanComponents["schemas"]["genre"][];
    };
    genre: {
      mal_id?: number;
      name?: string;
      url?: string;
      count?: number;
    };
    magazines: {
      data?: JikanComponents["schemas"]["magazine"][];
    } & JikanComponents["schemas"]["pagination"];
    magazine: {
      mal_id?: number;
      name?: string;
      url?: string;
      count?: number;
    };
    manga_characters: {
      data?: {
        character?: JikanComponents["schemas"]["character_meta"];
        role?: string;
      }[];
    };
    manga_search: {
      data?: JikanComponents["schemas"]["manga"][];
    } & JikanComponents["schemas"]["pagination_plus"];
    manga_full: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["manga_images"];
      approved?: boolean;
      titles?: JikanComponents["schemas"]["title"][];
      title?: string;
      title_english?: string | null;
      title_japanese?: string | null;
      title_synonyms?: string[];
      type?: "Manga" | "Novel" | "Light Novel" | "One-shot" | "Doujinshi" | "Manhua" | "Manhwa" | "OEL" | null;
      chapters?: number | null;
      volumes?: number | null;
      status?: "Finished" | "Publishing" | "On Hiatus" | "Discontinued" | "Not yet published";
      publishing?: boolean;
      published?: JikanComponents["schemas"]["daterange"];
      score?: number | null;
      scored_by?: number | null;
      rank?: number | null;
      popularity?: number | null;
      members?: number | null;
      favorites?: number | null;
      synopsis?: string | null;
      background?: string | null;
      authors?: JikanComponents["schemas"]["mal_url"][];
      serializations?: JikanComponents["schemas"]["mal_url"][];
      genres?: JikanComponents["schemas"]["mal_url"][];
      explicit_genres?: JikanComponents["schemas"]["mal_url"][];
      themes?: JikanComponents["schemas"]["mal_url"][];
      demographics?: JikanComponents["schemas"]["mal_url"][];
      relations?: {
        relation?: string;
        entry?: JikanComponents["schemas"]["mal_url"][];
      }[];
      external?: {
        name?: string;
        url?: string;
      }[];
    };
    manga: {
      mal_id?: number;
      url?: string;
      images?: JikanComponents["schemas"]["manga_images"];
      approved?: boolean;
      titles?: JikanComponents["schemas"]["title"][];
      title?: string;
      title_english?: string | null;
      title_japanese?: string | null;
      type?: "Manga" | "Novel" | "Light Novel" | "One-shot" | "Doujinshi" | "Manhua" | "Manhwa" | "OEL" | null;
      chapters?: number | null;
      volumes?: number | null;
      status?: "Finished" | "Publishing" | "On Hiatus" | "Discontinued" | "Not yet published";
      publishing?: boolean;
      published?: JikanComponents["schemas"]["daterange"];
      score?: number | null;
      scored_by?: number | null;
      rank?: number | null;
      popularity?: number | null;
      members?: number | null;
      favorites?: number | null;
      synopsis?: string | null;
      background?: string | null;
      authors?: JikanComponents["schemas"]["mal_url"][];
      serializations?: JikanComponents["schemas"]["mal_url"][];
      genres?: JikanComponents["schemas"]["mal_url"][];
      explicit_genres?: JikanComponents["schemas"]["mal_url"][];
      themes?: JikanComponents["schemas"]["mal_url"][];
      demographics?: JikanComponents["schemas"]["mal_url"][];
    };
    manga_statistics: {
      data?: {
        reading?: number;
        completed?: number;
        on_hold?: number;
        dropped?: number;
        plan_to_read?: number;
        total?: number;
        scores?: {
          score?: number;
          votes?: number;
          percentage?: number;
        }[];
      };
    };
    moreinfo: {
      data?: {
        moreinfo?: string | null;
      };
    };
    news: {
      data?: {
        mal_id?: number;
        url?: string;
        title?: string;
        date?: string;
        author_username?: string;
        author_url?: string;
        forum_url?: string;
        images?: JikanComponents["schemas"]["common_images"];
        comments?: number;
        excerpt?: string;
      }[];
    };
    person_anime: {
      data?: {
        position?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
      }[];
    };
    people_search: {
      data?: JikanComponents["schemas"]["person"][];
    } & JikanComponents["schemas"]["pagination_plus"];
    person_full: {
      mal_id?: number;
      url?: string;
      website_url?: string | null;
      images?: JikanComponents["schemas"]["people_images"];
      name?: string;
      given_name?: string | null;
      family_name?: string | null;
      alternate_names?: string[];
      birthday?: string | null;
      favorites?: number;
      about?: string | null;
      anime?: {
        position?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
      }[];
      manga?: {
        position?: string;
        manga?: JikanComponents["schemas"]["manga_meta"];
      }[];
      voices?: {
        role?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
        character?: JikanComponents["schemas"]["character_meta"];
      }[];
    };
    person_manga: {
      data?: {
        position?: string;
        manga?: JikanComponents["schemas"]["manga_meta"];
      }[];
    };
    person: {
      mal_id?: number;
      url?: string;
      website_url?: string | null;
      images?: JikanComponents["schemas"]["people_images"];
      name?: string;
      given_name?: string | null;
      family_name?: string | null;
      alternate_names?: string[];
      birthday?: string | null;
      favorites?: number;
      about?: string | null;
    };
    person_voice_acting_roles: {
      data?: {
        role?: string;
        anime?: JikanComponents["schemas"]["anime_meta"];
        character?: JikanComponents["schemas"]["character_meta"];
      }[];
    };
    pictures_variants: {
      data?: {
        images?: JikanComponents["schemas"]["common_images"];
      }[];
    };
    producers: {
      data?: JikanComponents["schemas"]["producer"][];
    } & JikanComponents["schemas"]["pagination"];
    producer_full: {
      mal_id?: number;
      url?: string;
      titles?: JikanComponents["schemas"]["title"][];
      images?: JikanComponents["schemas"]["common_images"];
      favorites?: number;
      count?: number;
      established?: string | null;
      about?: string | null;
      external?: {
        name?: string;
        url?: string;
      }[];
    };
    producer: {
      mal_id?: number;
      url?: string;
      titles?: JikanComponents["schemas"]["title"][];
      images?: JikanComponents["schemas"]["common_images"];
      favorites?: number;
      count?: number;
      established?: string | null;
      about?: string | null;
    };
    user_about: {
      data?: {
        about?: string | null;
      }[];
    };
    user_favorites: {
      anime?: ({
        type?: string;
        start_year?: number;
      } & JikanComponents["schemas"]["anime_meta"])[];
      manga?: ({
        type?: string;
        start_year?: number;
      } & JikanComponents["schemas"]["manga_meta"])[];
      characters?: (JikanComponents["schemas"]["character_meta"] & JikanComponents["schemas"]["mal_url_2"])[];
      people?: JikanComponents["schemas"]["character_meta"][];
    };
    user_profile_full: {
      mal_id?: number | null;
      username?: string;
      url?: string;
      images?: JikanComponents["schemas"]["user_images"];
      last_online?: string | null;
      gender?: string | null;
      birthday?: string | null;
      location?: string | null;
      joined?: string | null;
      statistics?: {
        anime?: {
          days_watched?: number;
          mean_score?: number;
          watching?: number;
          completed?: number;
          on_hold?: number;
          dropped?: number;
          plan_to_watch?: number;
          total_entries?: number;
          rewatched?: number;
          episodes_watched?: number;
        };
        manga?: {
          days_read?: number;
          mean_score?: number;
          reading?: number;
          completed?: number;
          on_hold?: number;
          dropped?: number;
          plan_to_read?: number;
          total_entries?: number;
          reread?: number;
          chapters_read?: number;
          volumes_read?: number;
        };
      };
      external?: {
        name?: string;
        url?: string;
      }[];
    };
    user_history: {
      data?: JikanComponents["schemas"]["history"][];
    };
    history: {
      entry?: JikanComponents["schemas"]["mal_url"];
      increment?: number;
      date?: string;
    };
    user_updates: {
      data?: {
        anime?: ({
          entry?: JikanComponents["schemas"]["anime_meta"];
        } & {
          score?: number | null;
          status?: string;
          episodes_seen?: number | null;
          episodes_total?: number | null;
          date?: string;
        })[];
        manga?: ({
          entry?: JikanComponents["schemas"]["manga_meta"];
        } & {
          score?: number | null;
          status?: string;
          chapters_read?: number | null;
          chapters_total?: number | null;
          volumes_read?: number | null;
          volumes_total?: number | null;
          date?: string;
        })[];
      };
    };
    user_profile: {
      mal_id?: number | null;
      username?: string;
      url?: string;
      images?: JikanComponents["schemas"]["user_images"];
      last_online?: string | null;
      gender?: string | null;
      birthday?: string | null;
      location?: string | null;
      joined?: string | null;
    };
    user_statistics: {
      data?: {
        anime?: {
          days_watched?: number;
          mean_score?: number;
          watching?: number;
          completed?: number;
          on_hold?: number;
          dropped?: number;
          plan_to_watch?: number;
          total_entries?: number;
          rewatched?: number;
          episodes_watched?: number;
        };
        manga?: {
          days_read?: number;
          mean_score?: number;
          reading?: number;
          completed?: number;
          on_hold?: number;
          dropped?: number;
          plan_to_read?: number;
          total_entries?: number;
          reread?: number;
          chapters_read?: number;
          volumes_read?: number;
        };
      };
    };
    recommendations: {
      data?: {
        mal_id?: string;
        entry?: (JikanComponents["schemas"]["anime_meta"] | JikanComponents["schemas"]["manga_meta"])[];
        content?: string;
        user?: JikanComponents["schemas"]["user_by_id"];
      }[];
    } & JikanComponents["schemas"]["pagination"];
    entry_recommendations: {
      data?: {
        entry?: JikanComponents["schemas"]["anime_meta"] | JikanComponents["schemas"]["manga_meta"];
      }[];
    };
    manga_review: {
      mal_id?: number;
      url?: string;
      type?: string;
      reactions?: {
        overall?: number;
        nice?: number;
        love_it?: number;
        funny?: number;
        confusing?: number;
        informative?: number;
        well_written?: number;
        creative?: number;
      };
      date?: string;
      review?: string;
      score?: number;
      tags?: string[];
      is_spoiler?: boolean;
      is_preliminary?: boolean;
    };
    anime_review: {
      mal_id?: number;
      url?: string;
      type?: string;
      reactions?: {
        overall?: number;
        nice?: number;
        love_it?: number;
        funny?: number;
        confusing?: number;
        informative?: number;
        well_written?: number;
        creative?: number;
      };
      date?: string;
      review?: string;
      score?: number;
      tags?: string[];
      is_spoiler?: boolean;
      is_preliminary?: boolean;
      episodes_watched?: number;
    };
    anime_reviews: {
      data?: ({
        user?: JikanComponents["schemas"]["user_meta"];
      } & JikanComponents["schemas"]["anime_review"])[];
    } & JikanComponents["schemas"]["pagination"];
    manga_reviews: {
      data?: ({
        user?: JikanComponents["schemas"]["user_meta"];
      } & JikanComponents["schemas"]["manga_review"])[];
    } & JikanComponents["schemas"]["pagination"];
    anime_userupdates: {
      data?: {
        user?: JikanComponents["schemas"]["user_meta"];
        score?: number | null;
        status?: string;
        episodes_seen?: number | null;
        episodes_total?: number | null;
        date?: string;
      }[];
    } & JikanComponents["schemas"]["pagination"];
    manga_userupdates: {
      data?: {
        user?: JikanComponents["schemas"]["user_meta"];
        score?: number | null;
        status?: string;
        volumes_read?: number;
        volumes_total?: number;
        chapters_read?: number;
        chapters_total?: number;
        date?: string;
      }[];
    } & JikanComponents["schemas"]["pagination"];
  };
  parameters: {
    continuing: boolean;
    limit: number;
    page: number;
    preliminary: boolean;
    sfw: boolean;
    spoilers: boolean;
    unapproved: boolean;
  };
}

export interface JikanOperations {
  getAnimeFullById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["anime_full"];
        };
      };
      400: {};
    };
  }>;
  getAnimeById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["anime"];
        };
      };
      400: {};
    };
  }>;
  getAnimeCharacters: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_characters"];
      };
      400: {};
    };
  }>;
  getAnimeStaff: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_staff"];
      };
      400: {};
    };
  }>;
  getAnimeEpisodes: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_episodes"];
      };
      400: {};
    };
  }>;
  getAnimeEpisodeById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["anime_episode"];
        };
      };
      400: {};
    };
  }>;
  getAnimeNews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_news"];
      };
      400: {};
    };
  }>;
  getAnimeForum: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "all" | "episode" | "other";
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["forum"];
      };
      400: {};
    };
  }>;
  getAnimeVideos: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_videos"];
      };
      400: {};
    };
  }>;
  getAnimeVideosEpisodes: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_videos_episodes"];
      };
      400: {};
    };
  }>;
  getAnimePictures: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["pictures_variants"];
      };
      400: {};
    };
  }>;
  getAnimeStatistics: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_statistics"];
      };
      400: {};
    };
  }>;
  getAnimeMoreInfo: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["moreinfo"];
      };
      400: {};
    };
  }>;
  getAnimeRecommendations: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["entry_recommendations"];
      };
      400: {};
    };
  }>;
  getAnimeUserUpdates: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_userupdates"];
      };
      400: {};
    };
  }>;
  getAnimeReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        preliminary?: JikanComponents["parameters"]["preliminary"];
        spoilers?: JikanComponents["parameters"]["spoilers"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_reviews"];
      };
      400: {};
    };
  }>;
  getAnimeRelations: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["relation"][];
        };
      };
    };
  }>;
  getAnimeThemes: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_themes"];
      };
      400: {};
    };
  }>;
  getAnimeExternal: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["external_links"];
      };
      400: {};
    };
  }>;
  getAnimeStreaming: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["external_links"];
      };
      400: {};
    };
  }>;
  getCharacterFullById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["character_full"];
        };
      };
      400: {};
    };
  }>;
  getCharacterById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["character"];
        };
      };
      400: {};
    };
  }>;
  getCharacterAnime: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["character_anime"];
      };
      400: {};
    };
  }>;
  getCharacterManga: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["character_manga"];
      };
      400: {};
    };
  }>;
  getCharacterVoiceActors: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["character_voice_actors"];
      };
      400: {};
    };
  }>;
  getCharacterPictures: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["character_pictures"];
      };
      400: {};
    };
  }>;
  getClubsById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["club"];
        };
      };
      400: {};
    };
  }>;
  getClubMembers: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["pagination"] & JikanComponents["schemas"]["club_member"];
      };
      400: {};
    };
  }>;
  getClubStaff: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["club_staff"];
      };
      400: {};
    };
  }>;
  getClubRelations: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["club_relations"];
      };
      400: {};
    };
  }>;
  getAnimeGenres: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: JikanComponents["schemas"]["genre_query_filter"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["genres"];
      };
      400: {};
    };
  }>;
  getMangaGenres: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: JikanComponents["schemas"]["genre_query_filter"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["genres"];
      };
      400: {};
    };
  }>;
  getMagazines: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        order_by?: JikanComponents["schemas"]["magazines_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["magazines"];
      };
      400: {};
    };
  }>;
  getMangaFullById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["manga_full"];
        };
      };
      400: {};
    };
  }>;
  getMangaById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["manga"];
        };
      };
      400: {};
    };
  }>;
  getMangaCharacters: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_characters"];
      };
      400: {};
    };
  }>;
  getMangaNews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_news"];
      };
      400: {};
    };
  }>;
  getMangaTopics: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "all" | "episode" | "other";
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["forum"];
      };
      400: {};
    };
  }>;
  getMangaPictures: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_pictures"];
      };
      400: {};
    };
  }>;
  getMangaStatistics: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_statistics"];
      };
      400: {};
    };
  }>;
  getMangaMoreInfo: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["moreinfo"];
      };
      400: {};
    };
  }>;
  getMangaRecommendations: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["entry_recommendations"];
      };
      400: {};
    };
  }>;
  getMangaUserUpdates: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_userupdates"];
      };
      400: {};
    };
  }>;
  getMangaReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        preliminary?: JikanComponents["parameters"]["preliminary"];
        spoilers?: JikanComponents["parameters"]["spoilers"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_reviews"];
      };
      400: {};
    };
  }>;
  getMangaRelations: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["relation"][];
        };
      };
      400: {};
    };
  }>;
  getMangaExternal: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["external_links"];
      };
      400: {};
    };
  }>;
  getPersonFullById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["person_full"];
        };
      };
      400: {};
    };
  }>;
  getPersonById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["person"];
        };
      };
      400: {};
    };
  }>;
  getPersonAnime: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["person_anime"];
      };
      400: {};
    };
  }>;
  getPersonVoices: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["person_voice_acting_roles"];
      };
      400: {};
    };
  }>;
  getPersonManga: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["person_manga"];
      };
      400: {};
    };
  }>;
  getPersonPictures: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["person_pictures"];
      };
      400: {};
    };
  }>;
  getProducerById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["producer"];
        };
      };
      400: {};
    };
  }>;
  getProducerFullById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["producer_full"];
        };
      };
      400: {};
    };
  }>;
  getProducerExternal: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["external_links"];
      };
      400: {};
    };
  }>;
  getRandomAnime: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["anime"];
        };
      };
      400: {};
    };
  }>;
  getRandomManga: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["manga"];
        };
      };
      400: {};
    };
  }>;
  getRandomCharacters: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["character"];
        };
      };
      400: {};
    };
  }>;
  getRandomPeople: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["person"];
        };
      };
      400: {};
    };
  }>;
  getRandomUsers: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["user_profile"];
        };
      };
      400: {};
    };
  }>;
  getRecentAnimeRecommendations: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["recommendations"];
      };
      400: {};
    };
  }>;
  getRecentMangaRecommendations: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["recommendations"];
      };
      400: {};
    };
  }>;
  getRecentAnimeReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        preliminary?: JikanComponents["parameters"]["preliminary"];
        spoilers?: JikanComponents["parameters"]["spoilers"];
      }>;
    };
    response: {
      200: {
        body: any;
      };
      400: {};
    };
  }>;
  getRecentMangaReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        preliminary?: JikanComponents["parameters"]["preliminary"];
        spoilers?: JikanComponents["parameters"]["spoilers"];
      }>;
    };
    response: {
      200: {
        body: any;
      };
      400: {};
    };
  }>;
  getSchedules: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday" | "unknown" | "other";
        kids?: "true" | "false";
        sfw?: "true" | "false";
        unapproved?: JikanComponents["parameters"]["unapproved"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["schedules"];
      };
      400: {};
    };
  }>;
  getAnimeSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        unapproved?: JikanComponents["parameters"]["unapproved"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        type?: JikanComponents["schemas"]["anime_search_query_type"];
        score?: number;
        min_score?: number;
        max_score?: number;
        status?: JikanComponents["schemas"]["anime_search_query_status"];
        rating?: JikanComponents["schemas"]["anime_search_query_rating"];
        sfw?: boolean;
        genres?: string;
        genres_exclude?: string;
        order_by?: JikanComponents["schemas"]["anime_search_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
        producers?: string;
        start_date?: string;
        end_date?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_search"];
      };
      400: {};
    };
  }>;
  getMangaSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        unapproved?: JikanComponents["parameters"]["unapproved"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        type?: JikanComponents["schemas"]["manga_search_query_type"];
        score?: number;
        min_score?: number;
        max_score?: number;
        status?: JikanComponents["schemas"]["manga_search_query_status"];
        sfw?: boolean;
        genres?: string;
        genres_exclude?: string;
        order_by?: JikanComponents["schemas"]["manga_search_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
        magazines?: string;
        start_date?: string;
        end_date?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_search"];
      };
      400: {};
    };
  }>;
  getPeopleSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        order_by?: JikanComponents["schemas"]["people_search_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["people_search"];
      };
      400: {};
    };
  }>;
  getCharactersSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        order_by?: JikanComponents["schemas"]["characters_search_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["characters_search"];
      };
      400: {};
    };
  }>;
  getUsersSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        gender?: JikanComponents["schemas"]["users_search_query_gender"];
        location?: string;
        maxAge?: number;
        minAge?: number;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["users_search"];
      };
      400: {};
    };
  }>;
  getUserById: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["user_by_id"];
        };
      };
      400: {};
    };
  }>;
  getClubsSearch: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        type?: JikanComponents["schemas"]["club_search_query_type"];
        category?: JikanComponents["schemas"]["club_search_query_category"];
        order_by?: JikanComponents["schemas"]["club_search_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["clubs_search"];
      };
      400: {};
    };
  }>;
  getProducers: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
        q?: string;
        order_by?: JikanComponents["schemas"]["producers_query_orderby"];
        sort?: JikanComponents["schemas"]["search_query_sort"];
        letter?: string;
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["producers"];
      };
      400: {};
    };
  }>;
  getSeasonNow: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "tv" | "movie" | "ova" | "special" | "ona" | "music";
        sfw?: JikanComponents["parameters"]["sfw"];
        unapproved?: JikanComponents["parameters"]["unapproved"];
        continuing?: JikanComponents["parameters"]["continuing"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_search"];
      };
      400: {};
    };
  }>;
  getSeason: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "tv" | "movie" | "ova" | "special" | "ona" | "music";
        sfw?: JikanComponents["parameters"]["sfw"];
        unapproved?: JikanComponents["parameters"]["unapproved"];
        continuing?: JikanComponents["parameters"]["continuing"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_search"];
      };
      400: {};
    };
  }>;
  getSeasonsList: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["seasons"];
      };
      400: {};
    };
  }>;
  getSeasonUpcoming: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        filter?: "tv" | "movie" | "ova" | "special" | "ona" | "music";
        sfw?: JikanComponents["parameters"]["sfw"];
        unapproved?: JikanComponents["parameters"]["unapproved"];
        continuing?: JikanComponents["parameters"]["continuing"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_search"];
      };
      400: {};
    };
  }>;
  getTopAnime: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        type?: JikanComponents["schemas"]["anime_search_query_type"];
        filter?: JikanComponents["schemas"]["top_anime_filter"];
        rating?: JikanComponents["schemas"]["anime_search_query_rating"];
        sfw?: boolean;
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["anime_search"];
      };
      400: {};
    };
  }>;
  getTopManga: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        type?: JikanComponents["schemas"]["manga_search_query_type"];
        filter?: JikanComponents["schemas"]["top_manga_filter"];
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["manga_search"];
      };
      400: {};
    };
  }>;
  getTopPeople: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["people_search"];
      };
      400: {};
    };
  }>;
  getTopCharacters: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        limit?: JikanComponents["parameters"]["limit"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["characters_search"];
      };
      400: {};
    };
  }>;
  getTopReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
        type?: JikanComponents["schemas"]["top_reviews_type_enum"];
        preliminary?: boolean;
        spoilers?: boolean;
      }>;
    };
    response: {
      200: {
        body: {
          data?: {
            data?: (({
              user?: JikanComponents["schemas"]["user_meta"];
            } & {
              anime?: JikanComponents["schemas"]["anime_meta"];
            } & JikanComponents["schemas"]["anime_review"]) | ({
              user?: JikanComponents["schemas"]["user_meta"];
            } & {
              manga?: JikanComponents["schemas"]["manga_meta"];
            } & JikanComponents["schemas"]["manga_review"]))[];
          } & JikanComponents["schemas"]["pagination"];
        };
      };
      400: {};
    };
  }>;
  getUserFullProfile: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["user_profile_full"];
        };
      };
      400: {};
    };
  }>;
  getUserProfile: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["user_profile"];
        };
      };
      400: {};
    };
  }>;
  getUserStatistics: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["user_statistics"];
      };
      400: {};
    };
  }>;
  getUserFavorites: HttpSchema.Method<{
    response: {
      200: {
        body: {
          data?: JikanComponents["schemas"]["user_favorites"];
        };
      };
      400: {};
    };
  }>;
  getUserUpdates: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["user_updates"];
      };
      400: {};
    };
  }>;
  getUserAbout: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["user_about"];
      };
      400: {};
    };
  }>;
  getUserHistory: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        type?: "anime" | "manga";
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["user_history"];
      };
      400: {};
    };
  }>;
  getUserFriends: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["user_friends"];
      };
      400: {};
    };
  }>;
  getUserAnimelist: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        status?: JikanComponents["schemas"]["user_anime_list_status_filter"];
      }>;
    };
    response: {
      200: {
        body: any;
      };
      400: {};
    };
  }>;
  getUserMangaList: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        status?: JikanComponents["schemas"]["user_manga_list_status_filter"];
      }>;
    };
    response: {
      200: {
        body: any;
      };
      400: {};
    };
  }>;
  getUserReviews: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: {
          data?: {
            data?: (({
              user?: JikanComponents["schemas"]["user_meta"];
            } & {
              anime?: JikanComponents["schemas"]["anime_meta"];
            } & JikanComponents["schemas"]["anime_review"]) | ({
              user?: JikanComponents["schemas"]["user_meta"];
            } & {
              manga?: JikanComponents["schemas"]["manga_meta"];
            } & JikanComponents["schemas"]["manga_review"]))[];
          } & JikanComponents["schemas"]["pagination"];
        };
      };
      400: {};
    };
  }>;
  getUserRecommendations: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["recommendations"];
      };
      400: {};
    };
  }>;
  getUserClubs: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["user_clubs"];
      };
      400: {};
    };
  }>;
  getUserExternal: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["external_links"];
      };
      400: {};
    };
  }>;
  getWatchRecentEpisodes: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["watch_episodes"];
      };
      400: {};
    };
  }>;
  getWatchPopularEpisodes: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["watch_episodes"];
      };
      400: {};
    };
  }>;
  getWatchRecentPromos: HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        page?: JikanComponents["parameters"]["page"];
      }>;
    };
    response: {
      200: {
        body: JikanComponents["schemas"]["watch_promos"];
      };
      400: {};
    };
  }>;
  getWatchPopularPromos: HttpSchema.Method<{
    response: {
      200: {
        body: JikanComponents["schemas"]["watch_promos"];
      };
      400: {};
    };
  }>;
}
